version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: link_manager_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
    container_name: link_manager
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 link_manager_site.wsgi:application"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

